blog2/urls.py
from django.urls import path
from . import views


app_name = 'blog'

urlpatterns = [
    path('', views.render_post, name='post'),
    path('<int:post_id>', views.post_detail , name='post_detail')
]

portafolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


from portfolio import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog2.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog2/models.py
import datetime
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog2/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models.fields import CharField ,URLField
from django.db.models.fields.files import ImageField

# Create your models here.

class Project(models.Model):
    title = CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images/')
    url = URLField(blank=True)

blog2/views.py
from django.shortcuts import render , get_object_or_404
from .models import Post


def render_post(request):
    print('test')
    posts = Post.objects.all()
    return render(request,'posts.html',{'posts':posts})

def post_detail(request,post_id):
    post = get_object_or_404(Post, pk = post_id)
    return render(request,'post_detail.html',{'post_id':post_id,'post':post},)

portfolio/views.py
from django.shortcuts import render
from .models import Project

def home(request):
    projects = Project.objects.all()
    return render(request,'home.html',{'projects':projects})

blog2/templates/post_detail.html
{% extends 'layout.html' %}

{% block content %}
  <div class="text-center">
    <h2>{{ post.title }}</h2>
    <h3 class="my-2 h5 text-muted">{{ post.date|date:'F jS Y' }}</h3>
  </div>

  <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid" />
  <div class="my-4">
    <p>{{ post.description|safe }}</p>
  </div>
{% endblock %}

blog2/templates/posts.html
{% extends 'layout.html' %}

{% block content %}
  <h1>post</h1>

  {% for post in posts %}
  <div class="p-3">
    <div class="card card-body bg-black">
      <div class="row">
        <div class="col-3">
          <img src="{{ post.image.url }}" alt="{{ post.title }}" class="img-fluid"/>
        </div>
        <div class="col-9">
          <h2>{{ post.title }}</h2>
          <p>{{ post.description|safe|truncatechars:100 }}</p>
          <h3>{{ post.date|date:'M d Y'|upper }}</h3>
          <a class="btn btn-primary" href="{% url 'blog:post_detail' post.id %}">ver</a>
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
  {% load static %}

  <header class="row bg-black">
    <div class="col-md-4">
      <img src="{% static 'cv/profile.jpeg' %}" alt="" />
    </div>

    <div class="col-md-8 my-auto">
      <h1>I am <strong>Miguel pasaje</strong></h1>
      <h3>I am a python Fullstak Developer</h3>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatum ipsum ullam exercitationem nesciunt excepturi veritatis in iure quod minima dignissimos eius quia quis totam error commodi reprehenderit iusto rem quos corporis, nobis ut velit? Quibusdam eum dignissimos, autem reiciendis consequatur totam recusandae ab! Veniam sunt maxime, delectus repellat dolorum cum? Eaque nesciunt itaque libero est doloribus consequuntur natus unde, sapiente error temporibus consectetur totam omnis dicta quas aut culpa, ipsum quisquam! Architecto nesciunt cupiditate culpa vitae sed consectetur quaerat ipsum, maiores tenetur nam voluptate quod alias, eius error? Enim, laborum. Vitae earum explicabo pariatur. Dolores eius neque quis harum magni.</p>
      <a class="btn btn-primary btn-lg rounded-0 my-3" href="{% static 'cv/cv.pdf' %}" target="_blank">Download CV</a>
    </div>
  </header>

  <div class="row my-4 text-center">
    <h3>my projects<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ea, voluptatibus.</p></h3>
  </div>

  <div class="row">
    {% for project in projects %}
      <div class="col-md-4 p-4">
        <div class="card bg-black card-project">
          <img src="{{ project.image.url }}" alt="{{ project.title }}" class="img-top" />
          <div class="card-body">
            <h2>{{ project.title }}</h2>
            <p>{{ project.description }}</p>
            {% if project.url %}
              <a class="btn btn-light rounded-0 btn-sm" target="_blank" href="{{ project.url }}">ir</a>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endblock %}

portfolio/templates/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous" />

    <link rel="stylesheet" href="{% static 'main.css' %}">
  </head>
  <body class="text-light">
    {% include 'partials/navbar.html' %}

    <div class="container">
      {% block content %}

      {% endblock %}
    </div>

    <footer>footer</footer>
  </body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand fw-bold fst-italic" href="/">MP</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ms-auto">         
          <li class="nav-item">
            <a class="nav-link" href="{% url 'blog:post' %}">blog</a>
          </li>
          <li class="nav-item d-flex align-items-center">
            <a class="btn btn-primary btn-sm" href="{% static 'cv/cv.pdf'%}" target="_blank">Download CV</a>
          </li>          
        </ul>
      </div>
    </div>
  </nav>